### ISSUE TITLE
ttgo t-beam lora issue

### ISSUE THREAD

**Issue by darkman7hr** [Bjoerns-TB/ttn-gps-tracker#2]
I'm getting strange gps readouts 
{
  "altitude": 167509.12,
  "hdop": 0.5,
  "latitude": -109.794,
  "longitude": 454.1587
}

then some other, then other.. hm. I did everything right

**Comment by Bjoerns-TB** [comment]
For the T_Beam i would suggest [this](https://github.com/DeuxVis/Lora-TTNMapper-T-Beam) repository.
