### ISSUE TITLE
Sketch Size Error

### ISSUE THREAD

**Issue by stmikul** [Bjoerns-TB/ttn-gps-tracker#5]
I'm using the Adafruit Feather 32u4 Lora with the Ultimate GPS featherwing as described in the documentation but I'm getting the following error compiling to the Feather 32u4.

_Sketch uses 30030 bytes (104%) of program storage space. Maximum is 28672 bytes.
Global variables use 1937 bytes of dynamic memory.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Adafruit Feather 32u4._

Any suggestions?

**Comment by ohobby** [comment]
+1
Same problem, no matter which lmic I use. :-(

**Comment by Bjoerns-TB** [comment]
Hi,

with
#define DISABLE_PING
#define DISABLE_BEACONS
in the lmic_project_config.h the tracker.ino will work.
